version: "3.8"

services:

  # BASE DE DATOS (NO SE CONSTRUYE)
  database:
    image: mysql:8
    container_name: sgu-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sgu_mfbr_10d
    ports:
      - "3307:3306"
    networks:
      - sgu-net
    volumes:
      - sgu-volume:/var/lib/mysql

  # FRONTEND – CLIENTE (SE CONSTRUYE)
  frontend:
    build:
      context: ./client
      args:
        # ✅ CAMBIO: Usar localhost porque el navegador accede desde el HOST
        API_HOST: localhost
        API_BASE: /api/users
        # ✅ Puerto mapeado al host (8081)
        API_PORT: 8081
    image: client:1.0-sgu
    container_name: sgu-frontend
    ports:
      - "3000:443"
    networks:
      - sgu-net
    volumes:
      -   certbot-conf:/etc/letsencrypt
    depends_on:
      - backend

  # BACKEND – SERVIDOR (SE CONSTRUYE)
  backend:
    build:
      context: ./server
    image: server:1.0-sgu
    container_name: sgu-backend
    environment:
      SERVER_PORT: 8080
      DB_HOST: sgu-database      
      DB_PORT: 3306
      DB_NAME: sgu_mfbr_10d
      DB_USER: root
      DB_PASS: root
      SERVER_SSL_ENABLED: true
      SERVER_SSL_KEYSTORE: /etc/letsencrypt/live/localhost/keystore.p12
      SERVER_SSL_KEYSTORE_PASSWORD: changeit
    ports:
      - "8081:8080"
    networks:
      - sgu-net
    volumes:
      -   certbot-conf:/etc/letsencrypt
    depends_on:
      - database

# VOLUMEN
volumes:
  sgu-volume:
    external: true
  certbot-conf:
    external: true 

# RED
networks:
  sgu-net:
    external: true